server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /authcore/api/ {
    proxy_pass http://authcore:8080/api/;
  }

  location /reserveo/api/ {
    proxy_pass http://reserveo-api:8081/api/;
  }
}
